# SonarQube server settings
sonar.host.url=https://sonarcloud.io
sonar.organization=dimid85-github
sonar.login=squ_938a621b64b06fdf4a244bf014e827fab29e14cd

# Project settings
sonar.projectKey=Dimid85_mySonarDemo1
sonar.projectName=mySonarDemo1
sonar.projectVersion=1.0

# Paths to sources and tests
sonar.sources=src
sonar.tests=tests
sonar.test.inclusions=**/*.spec.js,**/*.test.js

# Language
sonar.language=js
sonar.sourceEncoding=UTF-8

# Optional: Coverage settings
sonar.javascript.lcov.reportPaths=coverage/lcov-report/lcov.info

# Optional: ESLint integration
sonar.eslint.reportPaths=eslint-report.json
