name: SonarQube Analysis

on:
  push:
    branches:
      - main

jobs:
  sonarqube:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Build and Test
      run: |
        npm install
        npm run build
        npm test

    - name: SonarQube Scan
      uses: SonarSource/sonarqube-scan-action@v1
      with:
        sonar-token: ${{ secrets.USER_TOKEN }}
        sonar-project-key: ${{ github.repository }}
        sonar-github-token: ${{ secrets.TEST_TOKEN }}
        sonar-organization: dimid85-github
